// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWibF5Uc5y5tmMmsRztp4xisDEuTBDn6Q',
    appId: '1:561207833776:android:52ec483cc67b000308f775',
    messagingSenderId: '561207833776',
    projectId: 'dochat-49240',
    databaseURL: 'https://dochat-49240-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dochat-49240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHz7FUKMEC_sk3Htq7OIayA2WFARgHLeQ',
    appId: '1:561207833776:ios:3cb06e5210dc741008f775',
    messagingSenderId: '561207833776',
    projectId: 'dochat-49240',
    databaseURL: 'https://dochat-49240-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dochat-49240.appspot.com',
    androidClientId: '561207833776-vipl3hri8g2vcrfrqmgdcdkf76dfjeqs.apps.googleusercontent.com',
    iosClientId: '561207833776-6d7k1rg9gf85bug3c2alvir3fi02t6q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.doChat',
  );
}
